field.formatter.settings.geolocation_address:
  type: geolocation.field.formatter.map.base
  label: 'Geolocation Address Google Map formatter settings'
  mapping:
    data_provider_settings:
      label: 'Data provider settings'
      type: geolocation.data_provider.geolocation_address_field_provider
