plugin.plugin_configuration.geolocation.map_center_option.fixed_value:
  type: geolocation.map_center_option_settings
  label: 'Fixed Coordinates'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        latitude:
          type: float
          label: 'Latitude'
        longitude:
          type: float
          label: 'Longitude'

plugin.plugin_configuration.geolocation.map_center_option.fit_bounds:
  type: geolocation.map_center_option_settings
  label: 'Fit Locations'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        reset_zoom:
          type: boolean
          label: 'Reset zoom'
