plugin.plugin_configuration.geolocation.map_feature.leaflet_marker_popup:
  type: geolocation.map_feature_settings
  label: 'Marker Popup'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        info_auto_display:
          type: boolean
          label: 'Show info window on map start'

plugin.plugin_configuration.geolocation.map_feature.leaflet_marker_clusterer:
  type: geolocation.map_feature_settings
  label: 'Marker Clusterer'
